# -*- coding: utf-8 -*-
"""Practica 4 Calidad y mineria de datos .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7QPnB3K2cMkj9dsl6YejCbcmDWtnRO8

# Práctica 4: Calidad y Minería de datos - Python
Mariana Urrego, Natalia Urrego, Sebastian Villa, Steve Ellis

## Punto 1 - CALIDAD DE DATOS



Genere el perfilado de datos en Python sobre los datos originales, adjunte el resultado en HTML.

Realice un diagnóstico de cada una de las dimensiones de la calidad de datos, teniendo en cuenta los resultados del perfilado. El diagnóstico debe estar en el notebook.

Implemente todos los pasos de limpieza y mejora de los datos en Python.
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

data = pd.read_csv("cybersecurity_intrusion_data.csv", keep_default_na=False)
data.head()

data.info()

#Revisamos si tenemos ID repetidos
ids = data['session_id'].value_counts()
ids[ids > 1]

data['unusual_time_access'] = data['unusual_time_access'].astype('category')
data['attack_detected'] = data['attack_detected'].astype('category')

#Corrección tipo de datos
for column in data.columns:
    if data[column].dtype == 'object':
        data[column] = data[column].astype('category')

data.info( )

"""# 2. Eliminar variables irrelevantes y redundantes
* Irrelevantes: cedulas, ids, nombres, telefonos, direcciones, códigos.
* Redundantes: validación por fórmula matemática que están repetidas
"""

# Variables irrelevantes para el proceso de minería
data = data.drop('session_id',axis=1) #Eliminamos el ID por ser irrelevante, axis=1 indica que es una columna
data.head()

"""3. Descripción estadística

"""

data.describe()

"""**Variables numéricas**"""

data.hist()

data.plot.box()

"""Variables categóricas (value_counts())"""

#Conocemos las variables categóricas: bar, barh, pie
data['protocol_type'].value_counts().plot(kind='bar')

#Conocemos las variables categóricas: bar, barh, pie
data['encryption_used'].value_counts().plot(kind='barh')

"""Gráficas de las relaciones entre variables"""

#Conocemos las variables categóricas: bar, barh, pie

data.plot.scatter(x='browser_type',y='session_duration')

"""Perfilado de datos"""

!pip install ydata-profiling

from ydata_profiling import ProfileReport

profile_data=ProfileReport(data, minimal=True) # minimal=True
profile_data

#Guardamos en html el perfilado de datos
profile_data.to_file(output_file="output.html")

"""# **Dimensiones de la Calidad de Datos**

**Completitud:** ¿Está toda la información disponible? ¿Hay datos faltantes o ausentes?

**Exactitud:**¿La información es correcta y libre de error?

**Conformidad:** ¿Los valores de los datos están conformes con los formatos esperados? Ejemplo: Una fecha en formato AAAA/MM/DD cuando debería ser DD/MM/AAAA.

**Oportunidad:** ¿La información llega cuando se necesita?

**Duplicidad:** ¿Existen múltiples instancias, innecesarias de los mismos objetos de datos en el conjunto de datos?

**Integridad:** ¿Faltan datos relacionados importantes? ¿Es clara la conectividad y las relaciones con otros datos?

Diagnóstico de las dimensiones según el perfilado:

Completitud: Si, está todo disponible

Exactitud: La información es correcta

Conformidad: Si, todo en orden

Oportunidad: No aplica, no se puede verificar con los datos disponibles. En un entorno de producción real, esta dimensión sería crítica para sistemas de detección de intrusiones en tiempo real

Duplicidad: No hay problemas de duplicidad en el dataset.

Integridad: No se detectaron problemas de integridad. Las variables tienen relaciones lógicas claras dentro del contexto de ciberseguridad.

# 4. Limpieza de datos atípicos-errores
- Sólo se limpian errores

*No se eliminan, ya que los zeros en los registros indican ausencia de fallas al iniciar sesión, lo cual no es un mal registro. el ataque se llevó a cabo a el primer intento*

5. Limpieza de datos nulos: Imputación

Estrategia:

Eliminar registros con mas de 15% de nulos
Eliminar columnas con mas de 15%-20% de nulos
Imputar por media, moda, mediana, vecinos cercanos. No se puede imputar más allá del 15% de los datos.
Para casos especiales se crea modelo predictivo

6. Correlaciones para redundancias
"""

# Todas las variables deben ser numéricas para calcular las correlaciones
# Se crean dummies para las variables categóricas

data_num = pd.get_dummies(data, drop_first=True, dtype=int)
data_num.head()

"""Correlaciones para redundacia= mayores |0.8|"""

#Correlaciones
correlaciones=data_num.corr()
correlaciones

import seaborn as sns
plt.figure(figsize=(10,10))
sns.heatmap(data_num.corr(),annot=True)

#Correlaciones con la variable de objetivo
cor_variable_obj=correlaciones.loc['attack_detected_1']
cor_variable_obj

"""Las correlaciones de casi la mayoria de las variables es demasiado baja, pero no se eliminan ya que se quedaria sin variables, se eliminan solamente las que tienen un valor mas mas bajo de correlación."""

#Detección de irrelevantes = se buscan correlaciones con la variable objetivo muy bajas (0.0-0.05 ) ->ultima fila
columns_to_drop = ['protocol_type', 'network_packet_size', 'unusual_time_access']
data = data.drop(columns=columns_to_drop)
display(data.head())

"""# 8. Guardar los datos preparados"""

data.to_excel('./datos_limpios.xlsx')

"""FIN"""