# -*- coding: utf-8 -*-
"""DespliegueNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h728b3Gy6K_3O0XwHZmu_iFXX94gm-yS

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import pickle
filename = 'modelo-classNN.pkl'

# Cargamos el contenido del archivo pickle, que es una lista de 4 elementos
loaded_content = pickle.load(open(filename, 'rb'))

# Desempaquetamos los elementos de la lista en variables específicas
modelo, label_encoder, variables, min_max_scaler = loaded_content

# Puedes imprimir los tipos para verificar que se cargaron correctamente
print(f"Tipo de modelo: {type(modelo)}")
print(f"Tipo de label_encoder: {type(label_encoder)}")
print(f"Tipo de variables: {type(variables)}")
print(f"Tipo de min_max_scaler: {type(min_max_scaler)}")

#Cargamos los datos futuros
data = pd.read_csv("DatosFuturosP4.csv")
data.head()

data.info()



#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de Riesgo de Seguridad')

login_attempts = st.number_input('Número de intentos de inicio de sesión', min_value=0, value=5, step=1)
session_duration = st.number_input('Duración de la sesión (minutos)', min_value=0.0, value=450.5, step=0.1)
ip_reputation_score = st.number_input('Puntuación de reputación IP (0-1)', min_value=0.0, max_value=1.0, value=0.65, step=0.01)
failed_logins = st.number_input('Número de inicios de sesión fallidos', min_value=0, value=1, step=1)
encryption_used = st.selectbox('Cifrado utilizado', ['AES', 'DES', 'None'])
browser_type = st.selectbox('Tipo de navegador', ['Chrome', 'Firefox', 'Edge', 'Safari', 'Unknown'])


#Dataframe
datos = [[login_attempts, session_duration, ip_reputation_score, failed_logins, encryption_used, browser_type]]
data = pd.DataFrame(datos, columns=['login_attempts', 'session_duration', 'ip_reputation_score', 'failed_logins', 'encryption_used', 'browser_type']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

# En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['encryption_used', 'browser_type'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

# Identificamos las columnas numéricas que necesitan escalado (las que no son one-hot-encoded ni el objetivo)
numerical_cols = ['login_attempts', 'session_duration', 'ip_reputation_score', 'failed_logins']

# Aplicamos el scaler a todas las columnas numéricas de una vez
# Aseguramos que las columnas existen antes de intentar escalarlas

# Filtramos numerical_cols para incluir solo las que realmente están en data_preparada
existing_numerical_cols = [col for col in numerical_cols if col in data_preparada.columns]

if existing_numerical_cols:
    data_preparada[existing_numerical_cols] = min_max_scaler.transform(data_preparada[existing_numerical_cols])

data_preparada.head()

"""# Predicciones"""

# Hacemos la predicción con la Red Neuronal (NN)
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming 'attack_detected' is the true label and 'Prediccion' is the model's prediction
y_true = data['attack_detected']
y_pred = data['Prediccion']

# Generate a classification report
report = classification_report(y_true, y_pred, output_dict=True)
print("Classification Report:")
print(classification_report(y_true, y_pred))

# Generate a confusion matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 20%")