# -*- coding: utf-8 -*-
"""DespliegueNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h728b3Gy6K_3O0XwHZmu_iFXX94gm-yS

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import pickle
filename = 'modelo-classNN.pkl'

# Cargamos el contenido del archivo pickle, que es una lista de 4 elementos
loaded_content = pickle.load(open(filename, 'rb'))
modelo, label_encoder, variables, min_max_scaler = loaded_content

#Cargamos los datos futuros
#data = pd.read_csv("DatosFuturosP4.csv")
#data.head()

import streamlit as st

st.title('Predicción de Riesgo de Seguridad')

# Inputs para el modelo
login_attempts = st.number_input('Número de intentos de inicio de sesión', min_value=0, value=5, step=1)
session_duration = st.number_input('Duración de la sesión (minutos)', min_value=0.0, value=450.5, step=0.1)
ip_reputation_score = st.number_input('Puntuación de reputación IP (0-1)', min_value=0.0, max_value=1.0, value=0.65, step=0.01)
failed_logins = st.number_input('Número de inicios de sesión fallidos', min_value=0, value=1, step=1)
encryption_used = st.selectbox('Cifrado utilizado', ['AES', 'DES', 'None'])
browser_type = st.selectbox('Tipo de navegador', ['Chrome', 'Firefox', 'Edge', 'Safari', 'Unknown'])

# Botón para activar la predicción
predict_button = st.button('Realizar Predicción')

# Placeholder para mostrar la predicción (se actualizará después de la predicción)
prediction_placeholder = st.empty()

#Dataframe (solo se creará y procesará si el botón de predicción es presionado)
if predict_button:
    datos = [[login_attempts, session_duration, ip_reputation_score, failed_logins, encryption_used, browser_type]]
    data = pd.DataFrame(datos, columns=['login_attempts', 'session_duration', 'ip_reputation_score', 'failed_logins', 'encryption_used', 'browser_type'])
    # Aquí se debería llamar a la lógica de preparación y predicción
    # Para este ejemplo, solo mostraremos los datos crudos en el placeholder
    prediction_placeholder.write('Datos de entrada para la predicción:')
    prediction_placeholder.write(data)

#Se realiza la preparación
data_preparada=data.copy()

# En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['encryption_used', 'browser_type'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

# Identificamos las columnas numéricas que necesitan escalado (las que no son one-hot-encoded ni el objetivo)
numerical_cols = ['login_attempts', 'session_duration', 'ip_reputation_score', 'failed_logins']

# Aplicamos el scaler a todas las columnas numéricas de una vez
# Aseguramos que las columnas existen antes de intentar escalarlas

# Filtramos numerical_cols para incluir solo las que realmente están en data_preparada
existing_numerical_cols = [col for col in numerical_cols if col in data_preparada.columns]

if existing_numerical_cols:
    data_preparada[existing_numerical_cols] = min_max_scaler.transform(data_preparada[existing_numerical_cols])

data_preparada.head()

"""# Predicciones"""

# Hacemos la predicción con la Red Neuronal (NN)
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 20%")