# -*- coding: utf-8 -*-
"""Modelo predictivo .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLc8FAe9eU6NgoV6JXsHyNDL6mt7OfMB

# Predicción de ataque al corazón (Clasificación)

1. Preparación de Datos
2. División de los datos 70-30
3. Aprendizaje del Modelo
4. Evaluación del Modelo: matriz de confusion, P,R, ROC
5. Guardar el modelo

* El despliegue se realiza en otro jupyter_notebook
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

"""# 1. Preparación de Datos

"""

data = pd.read_excel("DatosLimpiosP4.xlsx", keep_default_na=False)
data.head()

data.info()

# Convertir 'attack_detected' a tipo categórico
data['attack_detected'] = data['attack_detected'].astype('category')

#Corrección tipo de datos
for column in data.columns:
    if data[column].dtype == 'object':
        data[column] = data[column].astype('category')

data.info()

#Descripción variables numérica
data.plot(kind='box')

#Descripción variables categóricas
data['encryption_used'].value_counts().plot(kind='bar')

#Descripción variables categóricas
data['browser_type'].value_counts().plot(kind='bar')

#Descripción variables categóricas
data['attack_detected'].value_counts().plot(kind='bar')

#La clase minoritaria tendrá el 50% del tamaño de la clase mayoritaria, adicionando datos sintéticos
from imblearn.over_sampling import SMOTE, SMOTENC

X = data.drop("attack_detected", axis = 1)
Y = data['attack_detected']

#K neighbours se configura de 2 a 7 entre menos mas parecido van a ser a los existentes

smote = SMOTENC(k_neighbors=2, categorical_features=[1,2,3,5], sampling_strategy=0.2)
X_smote, y_smote = smote.fit_resample(X,Y)

# Creamos un dataframe con los resultados (X_smote, y_smote)
data  = pd.DataFrame(columns=X_smote.columns.values, data=X_smote)
data['attack_detected']=y_smote
data['attack_detected'].value_counts().plot(kind='bar')

data.info()

#Dummies para las variables categóricas existentes
data = pd.get_dummies(data, columns=['encryption_used', 'browser_type'], drop_first=False, dtype=int)
data.head()

# la variable objetivo no se le hace dummies, se le hace label encoder

#LabelEncoder para la variable objetivo
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data["attack_detected"]=labelencoder.fit_transform(data["attack_detected"])
data.head()

"""# 2. División 70-30"""

#División 70-30
from sklearn.model_selection import train_test_split
X = data.drop("attack_detected", axis = 1) # Variables predictoras
Y = data['attack_detected'] #Variable objetivo
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, stratify=Y) #Muestreo estratificado    #en clasificación siempre se debe activar el muestreo estratificado
Y_train.value_counts().plot(kind='bar')

#Variable objetivo del 30%

Y_test.value_counts().plot(kind='bar')

"""# 3. Aprendizaje con el 70% y Evaluación con el 30%

# **Tree**
No se normaliza porque pierden interpretabilidad
"""

#Creación del modelo con el conjunto de entrenamiento
from sklearn.tree import DecisionTreeClassifier #DecisionTreeRegressor

modelTree = DecisionTreeClassifier(criterion='gini', min_samples_leaf=50, max_depth=10) #gini, entropy
modelTree.fit(X_train, Y_train) #70% train

from sklearn.tree import plot_tree
plt.figure(figsize=(30,20)) #Tamaño de la imagen
plot_tree(modelTree, feature_names=X_train.columns.values, class_names=[str(c) for c in labelencoder.classes_], rounded=True,  fontsize=8, filled=True)
plt.show()

#Evaluación 30% (X_test)
from sklearn import metrics

Y_pred = modelTree.predict(X_test) #30% Test
print(Y_pred)

#Exactitud: Correctos/Total
exactitud=metrics.accuracy_score(y_true=Y_test, y_pred=Y_pred)
print(exactitud)

#Matriz de confusion
from sklearn import metrics

cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
cm

#Plot de la matriz de confusion
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

metrics.RocCurveDisplay.from_estimator(modelTree,X_test, Y_test)

"""# **Random Forest**"""

#Random Forest
from sklearn.ensemble import RandomForestClassifier

model_rf= RandomForestClassifier(n_estimators=200,  max_samples=0.9, criterion='gini',                     #n_estimators es la cantidad de arboles
                              max_depth=20, min_samples_leaf=10)
model_rf.fit(X_train, Y_train) #70%

#Importancia de las características
importances = model_rf.feature_importances_
feature_names = X_train.columns
forest_importances = pd.Series(importances, index=feature_names)

fig, ax = plt.subplots()
forest_importances.sort_values(ascending=False).plot.bar(ax=ax)
ax.set_title("Importancia de las características (Random Forest)")
ax.set_ylabel("Importancia Media según el criterion")
fig.tight_layout()
plt.show()

#Evaluación de RandomForest con 30%
from sklearn import metrics

Y_pred = model_rf.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(model_rf,X_test, Y_test)

"""# **KNN**
* Normalización
"""

#Normalizacion las variables numéricas (las dummies no se normalizan)
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
variables_numericas=['login_attempts', 'session_duration', 'ip_reputation_score', 'failed_logins']


min_max_scaler.fit(data[variables_numericas]) #Ajuste de los parametros sobre 100% de los datos (data): max - min

#Se aplica la normalización a 70%  y 30%
X_train[variables_numericas]= min_max_scaler.transform(X_train[variables_numericas]) #70%
X_test[variables_numericas]= min_max_scaler.transform(X_test[variables_numericas]) #30%
X_train.head()

X_test.head()

#Aprendizaje KNN con 70%
from sklearn.neighbors  import KNeighborsClassifier #KNeighborsRegressor

modelKnn = KNeighborsClassifier(n_neighbors=3, metric='euclidean')#euclidean, minkowski
modelKnn.fit(X_train, Y_train) #70%

#Evaluación de Knn con 30%
from sklearn import metrics

Y_pred = modelKnn.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=labelencoder.classes_)
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelKnn,X_test, Y_test)

"""# **Red Neuronal**
- Normalizar
"""

#Red Neuronal

from sklearn.neural_network import MLPClassifier #MLPRegressor

#Solo se configura capas ocultas, no se configura capa de entrada y de salida
#activation -> función activación de la oculta: tanh, logistic, linear, relu
#hidden_layer_sizes=5,7 -> dos capas ocultas con 5 neuronas y 7 neuronas
#learning_rate-> tamaño del paso constante o decreciente (constant, adaptive)
#learning_rate_init-> valor tasa de aprendizaje
#momentum-> valor momentum
#max_iter-> iteaciones
#random_state-> semilla para generacion numeros seudoaletorios
modelNN = MLPClassifier(activation="logistic",hidden_layer_sizes=(50), learning_rate='constant',
                     learning_rate_init=0.02, momentum= 0.03, max_iter=500, random_state=3)

modelNN.fit(X_train, Y_train) #70% normalizados

#Loss es la desviación entre Y_train y el Y_pred
loss_values = modelNN.loss_curve_
plt.plot(loss_values)

#Evaluación de Red Neuronal
from sklearn import metrics

Y_pred = modelNN.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=[str(c) for c in labelencoder.classes_])
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelNN,X_test, Y_test)

#Imprimir el modelo
print(modelNN.coefs_)  # W
print(modelNN.intercepts_) # b

"""# **SVM**
-Normalizar
"""

#SVM
from sklearn.svm import SVC # SVR

modelSVM = SVC(kernel='rbf',C=1,class_weight="balanced") #'linear', 'poly'->degree=3, 'rbf', 'sigmoid', 'precomputed'
modelSVM.fit(X_train, Y_train) #70%

#Evaluación de SVM
from sklearn import metrics

Y_pred = modelSVM.predict(X_test) #30%

#Matriz de confusion
cm=metrics.confusion_matrix(y_true=Y_test, y_pred=Y_pred)
disp=metrics.ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=[str(c) for c in labelencoder.classes_])
disp.plot()

#Precision, Recall, f1, exactitud
print(metrics.classification_report( y_true=Y_test, y_pred=Y_pred, target_names=[str(c) for c in labelencoder.classes_]))

# Curva ROC
metrics.RocCurveDisplay.from_estimator(modelSVM,X_test, Y_test)

"""### Why Neural Network (modelNN) was chosen

The Neural Network (`modelNN`) was selected as the best performing model due to its competitive and strong performance across various metrics. It achieved an accuracy of 0.89, with a high precision of 0.99 for detecting attacks (Class 1), and a solid F1-score of 0.86. These results, combined with its ability to learn complex patterns, made it the preferred choice over other evaluated models like Decision Tree, Random Forest, KNN, and SVM.

### Hiperparametrización con GridSearchCV para la Red neuronal
"""

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

# `modelNNH` es solo un nombre para el estimador base, el GridSearchCV probará diferentes configuraciones
modelNNH = MLPClassifier(random_state=1) # Inicializar con un modelo base, random_state para reproducibilidad

# Definir los parámetros para MLPClassifier
random_state=[1] # Semilla para generar números pseudoaleatorios
solver=['sgd','adam'] # 'lbfgs' es un solver para MLPClassifier,
learning_rate=['constant', 'adaptive'] # Tasa de aprendizaje 'adaptive'
learning_rate_init=[0.4, 1.2, 1.6] # Valor de la tasa de aprendizaje
momentum=[0.3, 0.5] # Momentum 0-1
activation=['logistic', 'identity', 'relu'] # 'logistic', 'relu', 'identity', 'tanh'
hidden_layer_sizes=[4, 20,[8, 20]] # Neuronas de la capa oculta ((entrada+salida)/2) - usando tuplas como espera MLPClassifier
max_iter = [150, 350] # Iteraciones

# Definir el scoring y cv (folds de validación cruzada) para GridSearchCV
scoring = 'accuracy' # Métrica de scoring común para clasificación
cv = 3 # Número de folds de validación cruzada, se puede ajustar

#Grid
param_grid = dict(random_state=random_state,solver=solver,activation=activation, hidden_layer_sizes=hidden_layer_sizes, max_iter=max_iter, learning_rate=learning_rate,
                  learning_rate_init=learning_rate_init, momentum=momentum)
grid = GridSearchCV(estimator=modelNNH, param_grid=param_grid, scoring=scoring, n_jobs=-1, cv=cv)
# Modificación clave: usar X_train y Y_train (datos ya escalados) para el GridSearchCV
grid.fit(X_train, Y_train)

#Mejor modelo
modelNN= grid.best_estimator_

#Medida de evaluación del mejor modelo
# Asegurarse de que medidas_CV esté inicializado si aún no existe
if 'medidas_CV' not in locals():
    medidas_CV = {}
medidas_CV['NN']=grid.best_score_

# Mejores parámetros
print( grid.best_params_)

print(medidas_CV)

medidas_CV

"""# 5. Guardamos el mejor modelo
Se entrena modelo final con 100% de los datos (X,Y)

### Justificación de los Resultados de la Red Neuronal Hiperparametriada

Los resultados de la hiperparametrización con `GridSearchCV` para la Red Neuronal mostraron una precisión en validación cruzada (`best_score_`) del 72.7%, lo cual es inferior al 89% de precisión obtenido por el modelo de Red Neuronal inicial en el conjunto de prueba. Esta aparente disminución en el rendimiento se debe a varios factores:

1.  **Inestabilidad Numérica Durante la Búsqueda:** El proceso de `GridSearchCV` encontró dificultades numéricas (`ValueError: Solver produced non-finite parameter weights`) para varias combinaciones de hiperparámetros. Esto ocurrió particularmente con valores elevados de `learning_rate_init` y la función de activación `identity`, que pueden causar divergencia de los pesos en modelos que son sensibles a la escala de los datos o a un entrenamiento agresivo. A pesar de haber escalado `X_train` y `Y_train` para el `GridSearchCV`, algunas configuraciones seguían siendo numéricamente inestables.
2.  **Rango de Búsqueda de Hiperparámetros:** El espacio de búsqueda inicial, aunque fue modificado para ser más conservador en `learning_rate_init` e incluyó la función `relu`, pudo haber seleccionado una combinación (`'activation': 'identity'`, `'learning_rate_init': 1.2`) que, aunque fue la "mejor" dentro de las opciones estables encontradas por el `GridSearchCV` en ese momento, no superó al modelo base. La `identity` activation, combinada con una tasa de aprendizaje relativamente alta, es más susceptible a problemas de convergencia en comparación con `relu` o `logistic` con tasas de aprendizaje más moderadas.

En resumen, los errores y el `best_score_` más bajo sugieren que la búsqueda de hiperparámetros no logró identificar una configuración que mejorara consistentemente el rendimiento del modelo base, posiblemente debido a un espacio de búsqueda todavía subóptimo o la persistencia de inestabilidades numéricas con ciertas combinaciones.
"""

#Normalizar X en caso de ser necesario: Knn, NN, SVM, Reg
X[variables_numericas]= min_max_scaler.transform(X[variables_numericas])

"""si se selecciona arbol o random forest no se normaliza X"""

#Entrenamos modelo final
modelNN.fit(X, Y) #100%

import pickle
filename = 'modelo-classNN.pkl'
variables= X.columns._values
pickle.dump([modelNN, labelencoder,variables,min_max_scaler], open(filename, 'wb'))